M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Thu Feb 24 19:38:07 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-24T19:38:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X3.8435Y-2.4719
X3.9016Y-2.4719
T0
M30
